apiVersion: v1
kind: Pod
metadata:
    name: hello
spec:
    containers:
        - name: container-my-balancer
          image: zomgra/nginx-load-balancer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080